name: CI TEST BUILD
on:
    pull_request:
        # We don't need this to be run on all types of PR behavior
        # See https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request
        types:
          - opened
          - synchronize

jobs:
  ci-test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Install dependencies
        run: npm ci

      - name: Run npm build
        run: npm run docs:build
